In [3]:
import torch
import numpy as np
from sklearn.datasets import load_files
from glob import glob
import cv2 # type: ignore
import matplotlib.pyplot as plt
%matplotlib inline
import random
import os

In [4]:
#狗的数据集
def load_data(path): 
    data = load_files(path)
    dog_files = np.array(data['filenames'])
    dog_targets = torch.nn.functional.one_hot(torch.tensor(np.array(data['target'])).long(),133)  # 将类别转换成数组。
    print(dog_targets.shape)
    return dog_files,dog_targets
train_files,train_targets = load_data('./dogImages/train')
valid_files,valid_targets = load_data('./dogImages/valid')  
test_files,test_targets = load_data('./dogImages/test')
dog_names = [item[20:-1] for item in sorted(glob("./dogImages/train/*/"))]


torch.Size([6680, 133])
torch.Size([835, 133])
torch.Size([836, 133])


In [5]:
#人脸的数据集
random.seed(8675309)
human_files = np.array(glob("lfw/*/*"))
random.shuffle(human_files)  #type:ignore

In [6]:
#人脸检测模型加载
face_cascade = cv2.CascadeClassifier('./haarcascades/haarcascade_frontalface_alt.xml') # type: ignore


In [26]:
def face_detector(img_path):
    img = cv2.imread(img_path) #type:ignore
    if img is not None:
        gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY) #type:ignore
        faces = face_cascade.detectMultiScale(gray)
        print(faces)
        return faces
    #圈出模型识别出的人脸在图中位置。
    # for(x,y,w,h) in faces:
    #     cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),1) # type: ignore
    # cv_rgb = cv2.cvtColor(img,cv2.COLOR_BGR2RGB) # type: ignore
    # plt.imshow(cv_rgb)
    # plt.show()
    

In [27]:
face_detection = []
for i in human_files:
    for j in os.listdir(i):
        face_detection.append(face_detector(os.path.join(i,j)))

[[ 72  74 106 106]]
[[ 71  70 110 110]]
[[ 60  63 123 123]]
[[ 70  69 114 114]]
[[ 68  69 113 113]]
[[ 74  67 116 116]]
[[ 73  71 105 105]]
[[ 66  68 119 119]]
[[ 67  67 115 115]]
[[ 69  72 113 113]]
[[ 71  64 109 109]]
[[ 72  70 108 108]]
[[ 70  67 112 112]]
[[ 68  71 109 109]]
[[ 72  70 108 108]]
[[ 16  81  38  38]
 [ 74  70 108 108]]
[[ 73  70 112 112]]
[[ 72  69 111 111]]
[[ 66  65 120 120]]
[[ 74  72 105 105]]
[[ 68  67 113 113]]
[[ 71  68 112 112]
 [  5 137  57  57]]
[[ 73  69 114 114]]
[[ 67  69 113 113]]
[[ 62  63 129 129]]
[[ 72  73 104 104]]
[[ 68  68 117 117]]
[[ 67  67 116 116]]
[[ 64  60 130 130]]
[[ 73  71 108 108]]
[[ 72  71 110 110]]
[[ 68  68 116 116]]
[[ 68  65 119 119]]
[[ 67  69 113 113]]
[[ 74  74 102 102]]
[[ 65  63 129 129]]
[[ 68  67 117 117]]
[[ 67  67 118 118]]
[[ 64  63 124 124]]
[[ 69  67 113 113]]
[[ 71  72 103 103]]
[[ 67  62 124 124]]
[[ 69  69 111 111]]
[[ 67  67 117 117]]
[[ 70  68 112 112]]
[[ 69  68 111 111]]
[[ 66  68 117 117]]
[[ 71  68 109 109]]
[[